image:
- Visual Studio 2022
#- macOS
#- Ubuntu
environment:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build_script:
# https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
- winget install --id=Microsoft.DotNet.SDK.Preview  -e
- dotnet build src --configuration Release --verbosity quiet
- dotnet test src --configuration Release --no-build --no-restore

on_failure:
  - ps: Get-ChildItem *.received.* -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test: off
artifacts:
- path: nugets\*.nupkg